### ISSUE TITLE
[BUG]: CJS/ESM related TS issues

### ISSUE THREAD

**Issue by Maxim-Mazurok** [octokit/types.ts#650]
### What happened?

Hello, I don't skip libcheck in my TSC, and started getting these errors since that latest update (13.6.0):
```
node_modules/@octokit/core/dist-types/types.d.ts:1:31 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import * as OctokitTypes from "@octokit/types";
```

It was working fine on 13.5.0 before

See for details: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/1079 and https://github.com/Maxim-Mazurok/google-api-typings-generator/actions/runs/11089432725/job/30810552166?pr=1079#step:5:1

### Versions

@octokit/types: 13.6.0 (all worked fine with 13.5.0)

@octokit/core: 5.2.0
@octokit/graphql: 7.1.0
@octokit/plugin-paginate-rest: 11.3.1
@octokit/plugin-rest-endpoint-methods: 13.2.2
@octokit/request: 8.4.0
@octokit/request-error: 5.1.0

### Relevant log output

```shell
> tsc --noEmit

node_modules/@octokit/core/dist-types/types.d.ts:1:31 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import * as OctokitTypes from "@octokit/types";
                                ~~~~~~~~~~~~~~~~

node_modules/@octokit/graphql/dist-types/error.d.ts:1:38 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { ResponseHeaders } from "@octokit/types";
                                       ~~~~~~~~~~~~~~~~

node_modules/@octokit/graphql/dist-types/types.d.ts:1:101 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { EndpointOptions, RequestParameters as RequestParametersType, EndpointInterface } from "@octokit/types";
                                                                                                      ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-paginate-rest/dist-types/generated/paginating-endpoints.d.ts:1:32 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { Endpoints } from "@octokit/types";
                                 ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-paginate-rest/dist-types/types.d.ts:2:31 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

2 import * as OctokitTypes from "@octokit/types";
                                ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-paginate-rest/dist-types/types.d.ts:3:100 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

3 export type { EndpointOptions, RequestInterface, OctokitResponse, RequestParameters, Route, } from "@octokit/types";
                                                                                                     ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/method-types.d.ts:1:58 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { EndpointInterface, RequestInterface } from "@octokit/types";
                                                           ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1:51 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { Endpoints, RequestParameters } from "@octokit/types";
                                                    ~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/types.d.ts:1:47 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { Route, RequestParameters } from "@octokit/types";
                                                ~~~~~~~~~~~~~~~~

node_modules/@octokit/request-error/dist-types/index.d.ts:1:71 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { RequestOptions, ResponseHeaders, OctokitResponse } from "@octokit/types";
                                                                        ~~~~~~~~~~~~~~~~

node_modules/@octokit/request-error/dist-types/types.d.ts:1:71 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 import type { RequestOptions, ResponseHeaders, OctokitResponse } from "@octokit/types";
                                                                        ~~~~~~~~~~~~~~~~

node_modules/@octokit/request/dist-types/index.d.ts:1:38 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/types")' call instead.

1 export declare const request: import("@octokit/types").RequestInterface<object>;
                                       ~~~~~~~~~~~~~~~~


Found 12 errors in 11 files.

Errors  Files
     1  node_modules/@octokit/core/dist-types/types.d.ts:1
     1  node_modules/@octokit/graphql/dist-types/error.d.ts:1
     1  node_modules/@octokit/graphql/dist-types/types.d.ts:1
     1  node_modules/@octokit/plugin-paginate-rest/dist-types/generated/paginating-endpoints.d.ts:1
     2  node_modules/@octokit/plugin-paginate-rest/dist-types/types.d.ts:2
     1  node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/method-types.d.ts:1
     1  node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1
     1  node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/types.d.ts:1
     1  node_modules/@octokit/request-error/dist-types/index.d.ts:1
     1  node_modules/@octokit/request-error/dist-types/types.d.ts:1
     1  node_modules/@octokit/request/dist-types/index.d.ts:1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kanadgupta** [comment]
ATTW is a good resource for validating types and that also seems to indicate that `@octokit/types@13.6.0` shipped bad types:

https://arethetypeswrong.github.io/?p=@octokit/types@13.5.0
https://arethetypeswrong.github.io/?p=@octokit/types@13.6.0

**Comment by Maxim-Mazurok** [comment]
Could be related: https://github.com/octokit/types.ts/pull/610/files#r1773781702

**Comment by wolfy1339** [comment]
It is a type only package after all, ESM vs CJS it doesn't matter.

Please note that it is not advised to depend on `@octokit/types` in your package, as having multiple versions can negatively affect your typescript experience. The types are closely tied to each version of the rest plugins

I do know about ATTW.

I will have a patch to fix these issues ASAP

**Comment by Maxim-Mazurok** [comment]
Yeah, I do not depend on this package directly, but I compile my dependencies that do (using `skipLibCheck: false`)

Thanks for the prompt response and PR!

**Comment by oscard0m** [comment]
@Maxim-Mazurok thanks for reporting this and thanks @wolfy1339 for the PR. 

@Maxim-Mazurok now we need Renovate to wait to do its job and merge all the subsequent PRs. As soon as everything is published, let us know if it solves your issue.

**Comment by wolfy1339** [comment]
They are using the previous version of the Octokit libraries that is still CJS. They won't get a new version from these updates.
