### ISSUE TITLE
regression: unused import causing downstream typecheck failure

### ISSUE THREAD

**Issue by AviVahl** [octokit/types.ts#51]
**What happened?**
After upgrading to 2.11.0, my build started failing with:
```
> tsc --noEmit
node_modules/@octokit/types/src/RequestInterface.ts:2:1 - error TS6133: 'EndpointOptions' is declared but its value is never read.
2 import { EndpointOptions } from "./EndpointOptions";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**What did you expect to happen?**
Pass type checking when imported from my project, even if my `tsconfig.json` is strict.

**What the problem might be**
My `tsconfig.json` file has the following 4 strict options turned on: 
- noUnusedLocals
- noUnusedParameters
- noImplicitReturns
- noFallthroughCasesInSwitch

`@octokit/types` is published as `.ts` files, which causes my typescript to check it (using *my* `tsconfig.json`) when imported via `node_modules`.

Workaround: remove unused import and republish.
More permanent solutions (to avoid similar issues):
- add a `tsconfig.json` to repo with strict options all turned on. this way, you'd know code is compatible.
- build package using tsc and publish the .d.ts files.

**Comment by AviVahl** [comment]
FYI @gr2m
this seems to have been broken by recent commit which removed the usage, but left import intact: https://github.com/octokit/types.ts/commit/17acf10abd50666cee6a11c35bd630e1695635ca#diff-3c45c4c35b2bc01e2dd2cb7b81547045R15

**Comment by gr2m** [comment]
thanks for reporting the problem, sorry for that!

I've added a test file at https://github.com/octokit/types.ts/blob/master/test.ts which I hoped would catch problems like this before the release :(

I'm looking into it

**Comment by gr2m** [comment]
Should be fixed via #52, release is on its way. I've only added the `noUnusedLocals` flag, the rest is relevant to code only, I think. Would you add any other flags? I prefer have the checks to be strict, but don't want to add types that don't really add any value

**Comment by AviVahl** [comment]
thanks for the quick fix! :) `"noUnusedLocals"` should do the job in this case.
